// SPDX-License-Identifier: MIT
use std::{fs, path::Path, path::PathBuf};

use anyhow::Result;
use luma_core::{
    AppId, LumaPlugin, Palette, Platform, SyncContext, THEME_NAME, TerminalUi, write_if_changed,
};

#[derive(Debug, Default)]
pub struct K9s;

impl LumaPlugin for K9s {
    fn name(&self) -> &'static str {
        "k9s"
    }

    fn sync(&self, ctx: &SyncContext) -> Result<()> {
        ensure_k9s_config(ctx)?;
        write_k9s_skin(ctx, THEME_NAME)
    }
}

impl TerminalUi for K9s {}

pub fn k9s_config_file(platform: &dyn Platform) -> Result<PathBuf> {
    Ok(platform
        .app_config_files(AppId::K9s, Path::new("config.yaml"))?
        .into_iter()
        .next()
        .expect("k9s config path exists"))
}

pub fn k9s_skin_file(platform: &dyn Platform, name: &str) -> Result<PathBuf> {
    Ok(platform
        .app_config_files(AppId::K9s, Path::new(&format!("skins/{name}.yaml")))?
        .into_iter()
        .next()
        .expect("k9s skin path exists"))
}

fn ensure_k9s_config(ctx: &SyncContext) -> Result<()> {
    let path = k9s_config_file(ctx.platform)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let original = fs::read_to_string(&path).unwrap_or_else(|_| "k9s:\n".to_string());
    let mut lines: Vec<String> = original.lines().map(ToOwned::to_owned).collect();
    if lines.is_empty() {
        lines.push("k9s:".to_string());
    }
    if lines.first().is_none_or(|line| line.trim() != "k9s:") {
        lines.insert(0, "k9s:".to_string());
    }

    lines.retain(|line| !line.starts_with("  skin:"));

    let ui_idx = if let Some(idx) = lines.iter().position(|line| line.starts_with("  ui:")) {
        idx
    } else {
        lines.insert(1, "  ui:".to_string());
        1
    };

    let mut end = lines.len();
    for (idx, line) in lines.iter().enumerate().skip(ui_idx + 1) {
        if line.starts_with("  ") && !line.starts_with("    ") && !line.trim().is_empty() {
            end = idx;
            break;
        }
    }

    let mut block = lines[ui_idx + 1..end].to_vec();
    set_ui_key(&mut block, "skin", THEME_NAME);
    set_ui_key(&mut block, "reactive", "true");
    lines.splice(ui_idx + 1..end, block);

    let next = format!("{}\n", lines.join("\n"));
    write_if_changed(&path, &next)
}

fn set_ui_key(block: &mut Vec<String>, key: &str, value: &str) {
    let prefix = format!("    {key}:");
    if let Some(line) = block.iter_mut().find(|line| line.starts_with(&prefix)) {
        *line = format!("    {key}: {value}");
    } else {
        block.insert(0, format!("    {key}: {value}"));
    }
}

fn write_k9s_skin(ctx: &SyncContext, name: &str) -> Result<()> {
    let path = k9s_skin_file(ctx.platform, name)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let text = render_k9s_skin(&ctx.palette);

    // Avoid waking K9s for duplicate syncs: reloading a skin makes K9s reset
    // cluster info and rebuild the active view, which is noticeably slower than
    // Luma's file generation.
    write_if_changed(&path, &text)
}

fn render_k9s_skin(p: &Palette) -> String {
    let accent_fg = &p.bg1;
    let focus_fg = if p.light { &p.fg1 } else { &p.bg1 };
    format!(
        r##"# Generated by Luma. Do not edit directly.
# K9s {name} skin, matching the selected Nightfox theme.
# Use terminal defaults for primary fg/bg so Ghostty/terminal appearance
# changes recolor the main K9s text immediately. Accent/panel colors below
# still reload through K9s' reactive skin watcher.
background: &background "default"
foreground: &foreground "default"
background-darker: &background-darker "{bg0}"
background-soft: &background-soft "{bg2}"
selection: &selection "{sel1}"
border: &border "{bg4}"
comment: &comment "{comment}"
accent-foreground: &accent-foreground "{accent_fg}"
focus-foreground: &focus-foreground "{focus_fg}"
black: &black "{black}"
red: &red "{red}"
green: &green "{green}"
yellow: &yellow "{yellow}"
blue: &blue "{blue}"
magenta: &magenta "{magenta}"
cyan: &cyan "{cyan}"
white: &white "{white}"
orange: &orange "{orange}"
pink: &pink "{pink}"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
    logoColorMsg: *foreground
    logoColorInfo: *green
    logoColorWarn: *yellow
    logoColorError: *red
  prompt:
    fgColor: *foreground
    bgColor: *background-darker
    suggestColor: *blue
    border:
      command: *blue
      default: *border
  help:
    fgColor: *foreground
    bgColor: *background
    sectionColor: *magenta
    keyColor: *blue
    numKeyColor: *pink
  frame:
    title:
      fgColor: *blue
      bgColor: *background-darker
      highlightColor: *pink
      counterColor: *orange
      filterColor: *green
    border:
      fgColor: *border
      focusColor: *blue
    menu:
      fgColor: *foreground
      keyColor: *blue
      numKeyColor: *pink
    crumbs:
      fgColor: *accent-foreground
      bgColor: *blue
      activeColor: *orange
    status:
      newColor: *blue
      modifyColor: *green
      addColor: *blue
      pendingColor: *yellow
      errorColor: *red
      highlightColor: *cyan
      killColor: *magenta
      completedColor: *comment
  info:
    sectionColor: *foreground
    fgColor: *orange
    cpuColor: *green
    memColor: *cyan
    k9sRevColor: *blue
  views:
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *foreground
      cursorBgColor: *selection
      markColor: *green
      header:
        fgColor: *blue
        bgColor: *background-darker
        sorterColor: *cyan
        selectedSortColumnColor: *pink
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *selection
      cursorTextColor: *foreground
      graphicColor: *comment
    charts:
      bgColor: *background
      dialBgColor: *background-darker
      chartBgColor: *background-darker
      focusFgColor: *focus-foreground
      focusBgColor: *orange
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *blue
        - *red
      resourceColors:
        cpu:
          - *blue
          - *magenta
        mem:
          - *yellow
          - *orange
    yaml:
      keyColor: *blue
      valueColor: *foreground
      colonColor: *comment
    picker:
      mainColor: *foreground
      focusColor: *blue
      shortcutColor: *pink
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *cyan
        bgColor: *background
        toggleOnColor: *green
        toggleOffColor: *comment
  dialog:
    fgColor: *foreground
    bgColor: *background-darker
    buttonFgColor: *accent-foreground
    buttonBgColor: *blue
    buttonFocusFgColor: *accent-foreground
    buttonFocusBgColor: *magenta
    labelFgColor: *foreground
    fieldFgColor: *cyan
"##,
        name = p.name,
        bg0 = p.bg0,
        bg2 = p.bg2,
        bg4 = p.bg4,
        sel1 = p.sel1,
        comment = p.comment,
        accent_fg = accent_fg,
        focus_fg = focus_fg,
        black = p.black,
        red = p.red,
        green = p.green,
        yellow = p.yellow,
        blue = p.blue,
        magenta = p.magenta,
        cyan = p.cyan,
        white = p.white,
        orange = p.orange,
        pink = p.pink,
    )
}
