// SPDX-License-Identifier: MIT
use std::{fs, path::Path, path::PathBuf};

use anyhow::Result;
use luma_core::{
    AppId, LumaPlugin, Palette, Platform, SyncContext, THEME_NAME, TerminalUi,
    primary_app_config_file, read_optional_text, write_if_changed,
};

#[derive(Debug, Default)]
pub struct K9s;

impl LumaPlugin for K9s {
    fn name(&self) -> &'static str {
        "k9s"
    }

    fn sync(&self, ctx: &SyncContext) -> Result<()> {
        ensure_k9s_config(ctx)?;
        write_k9s_skin(ctx, THEME_NAME)
    }
}

impl TerminalUi for K9s {}

pub fn k9s_config_file(platform: &dyn Platform) -> Result<PathBuf> {
    primary_app_config_file(platform, AppId::K9s, Path::new("config.yaml"))
}

pub fn k9s_skin_file(platform: &dyn Platform, name: &str) -> Result<PathBuf> {
    primary_app_config_file(
        platform,
        AppId::K9s,
        Path::new(&format!("skins/{name}.yaml")),
    )
}

fn ensure_k9s_config(ctx: &SyncContext) -> Result<()> {
    let path = k9s_config_file(ctx.platform)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let original = read_optional_text(&path)?.unwrap_or_else(|| "k9s:\n".to_string());
    let mut lines: Vec<String> = original.lines().map(ToOwned::to_owned).collect();
    if lines.is_empty() {
        lines.push("k9s:".to_string());
    }
    if lines.first().is_none_or(|line| line.trim() != "k9s:") {
        lines.insert(0, "k9s:".to_string());
    }

    lines.retain(|line| !line.starts_with("  skin:"));

    let ui_idx = if let Some(idx) = lines.iter().position(|line| line.starts_with("  ui:")) {
        idx
    } else {
        lines.insert(1, "  ui:".to_string());
        1
    };

    let mut end = lines.len();
    for (idx, line) in lines.iter().enumerate().skip(ui_idx + 1) {
        if line.starts_with("  ") && !line.starts_with("    ") && !line.trim().is_empty() {
            end = idx;
            break;
        }
    }

    let mut block = lines[ui_idx + 1..end].to_vec();
    set_ui_key(&mut block, "skin", THEME_NAME);
    set_ui_key(&mut block, "reactive", "true");
    lines.splice(ui_idx + 1..end, block);

    let next = format!("{}\n", lines.join("\n"));
    write_if_changed(&path, &next)
}

fn set_ui_key(block: &mut Vec<String>, key: &str, value: &str) {
    let prefix = format!("    {key}:");
    if let Some(line) = block.iter_mut().find(|line| line.starts_with(&prefix)) {
        *line = format!("    {key}: {value}");
    } else {
        block.insert(0, format!("    {key}: {value}"));
    }
}

fn write_k9s_skin(ctx: &SyncContext, name: &str) -> Result<()> {
    let path = k9s_skin_file(ctx.platform, name)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let text = render_k9s_skin(&ctx.palette);

    // Avoid waking K9s for duplicate syncs: reloading a skin makes K9s reset
    // cluster info and rebuild the active view, which is noticeably slower than
    // Luma's file generation.
    write_if_changed(&path, &text)
}

fn render_k9s_skin(p: &Palette) -> String {
    let accent_fg = &p.bg1;
    let focus_fg = if p.light { &p.fg1 } else { &p.bg1 };
    format!(
        r##"# Generated by Luma. Do not edit directly.
# K9s {name} skin, matching the selected Nightfox theme.
# Use terminal defaults for primary fg/bg so Ghostty/terminal appearance
# changes recolor the main K9s text immediately. Accent/panel colors below
# still reload through K9s' reactive skin watcher.
background: &background "default"
foreground: &foreground "default"
background-darker: &background-darker "{bg0}"
background-soft: &background-soft "{bg2}"
selection: &selection "{sel1}"
border: &border "{bg4}"
comment: &comment "{comment}"
accent-foreground: &accent-foreground "{accent_fg}"
focus-foreground: &focus-foreground "{focus_fg}"
black: &black "{black}"
red: &red "{red}"
green: &green "{green}"
yellow: &yellow "{yellow}"
blue: &blue "{blue}"
magenta: &magenta "{magenta}"
cyan: &cyan "{cyan}"
white: &white "{white}"
orange: &orange "{orange}"
pink: &pink "{pink}"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
    logoColorMsg: *foreground
    logoColorInfo: *green
    logoColorWarn: *yellow
    logoColorError: *red
  prompt:
    fgColor: *foreground
    bgColor: *background-darker
    suggestColor: *blue
    border:
      command: *blue
      default: *border
  help:
    fgColor: *foreground
    bgColor: *background
    sectionColor: *magenta
    keyColor: *blue
    numKeyColor: *pink
  frame:
    title:
      fgColor: *blue
      bgColor: *background-darker
      highlightColor: *pink
      counterColor: *orange
      filterColor: *green
    border:
      fgColor: *border
      focusColor: *blue
    menu:
      fgColor: *foreground
      keyColor: *blue
      numKeyColor: *pink
    crumbs:
      fgColor: *accent-foreground
      bgColor: *blue
      activeColor: *orange
    status:
      newColor: *blue
      modifyColor: *green
      addColor: *blue
      pendingColor: *yellow
      errorColor: *red
      highlightColor: *cyan
      killColor: *magenta
      completedColor: *comment
  info:
    sectionColor: *foreground
    fgColor: *orange
    cpuColor: *green
    memColor: *cyan
    k9sRevColor: *blue
  views:
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *foreground
      cursorBgColor: *selection
      markColor: *green
      header:
        fgColor: *blue
        bgColor: *background-darker
        sorterColor: *cyan
        selectedSortColumnColor: *pink
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *selection
      cursorTextColor: *foreground
      graphicColor: *comment
    charts:
      bgColor: *background
      dialBgColor: *background-darker
      chartBgColor: *background-darker
      focusFgColor: *focus-foreground
      focusBgColor: *orange
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *blue
        - *red
      resourceColors:
        cpu:
          - *blue
          - *magenta
        mem:
          - *yellow
          - *orange
    yaml:
      keyColor: *blue
      valueColor: *foreground
      colonColor: *comment
    picker:
      mainColor: *foreground
      focusColor: *blue
      shortcutColor: *pink
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *cyan
        bgColor: *background
        toggleOnColor: *green
        toggleOffColor: *comment
  dialog:
    fgColor: *foreground
    bgColor: *background-darker
    buttonFgColor: *accent-foreground
    buttonBgColor: *blue
    buttonFocusFgColor: *accent-foreground
    buttonFocusBgColor: *magenta
    labelFgColor: *foreground
    fieldFgColor: *cyan
"##,
        name = p.name,
        bg0 = p.bg0,
        bg2 = p.bg2,
        bg4 = p.bg4,
        sel1 = p.sel1,
        comment = p.comment,
        accent_fg = accent_fg,
        focus_fg = focus_fg,
        black = p.black,
        red = p.red,
        green = p.green,
        yellow = p.yellow,
        blue = p.blue,
        magenta = p.magenta,
        cyan = p.cyan,
        white = p.white,
        orange = p.orange,
        pink = p.pink,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use luma_core::{Mode, OsKind, ThemeConfig};
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(name: &str) -> Result<Self> {
            let unique = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock is before UNIX_EPOCH")
                .as_nanos();
            let path = std::env::temp_dir()
                .join(format!("luma-tui-{name}-{}-{unique}", std::process::id()));
            fs::create_dir_all(&path)?;
            Ok(Self(path))
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    struct FakePlatform {
        root: PathBuf,
    }

    impl Platform for FakePlatform {
        fn os_kind(&self) -> OsKind {
            OsKind::Unknown
        }

        fn home_dir(&self) -> Result<PathBuf> {
            Ok(self.root.clone())
        }

        fn app_config_files(&self, app: AppId, relative: &Path) -> Result<Vec<PathBuf>> {
            Ok(vec![self.root.join(format!("{app:?}")).join(relative)])
        }

        fn app_cache_file(&self, app: AppId, relative: &Path) -> Result<PathBuf> {
            Ok(self
                .root
                .join("cache")
                .join(format!("{app:?}"))
                .join(relative))
        }
    }

    #[test]
    fn k9s_config_updates_ui_without_dropping_other_sections() -> Result<()> {
        let temp = TempDir::new("config-update")?;
        let platform = FakePlatform {
            root: temp.0.clone(),
        };
        let config_path = k9s_config_file(&platform)?;
        fs::create_dir_all(config_path.parent().expect("config path has a parent"))?;
        fs::write(
            &config_path,
            "k9s:\n  ui:\n    skin: old\n    reactive: false\n  logger:\n    tail: 10\n",
        )?;
        let ctx = SyncContext::new(Mode::Light, ThemeConfig::default(), &platform)?;

        ensure_k9s_config(&ctx)?;

        let next = fs::read_to_string(config_path)?;
        assert!(next.contains("    skin: luma"));
        assert!(next.contains("    reactive: true"));
        assert!(next.contains("  logger:\n    tail: 10"));
        Ok(())
    }

    #[test]
    fn invalid_k9s_config_utf8_is_not_overwritten() -> Result<()> {
        let temp = TempDir::new("invalid-utf8")?;
        let platform = FakePlatform {
            root: temp.0.clone(),
        };
        let config_path = k9s_config_file(&platform)?;
        fs::create_dir_all(config_path.parent().expect("config path has a parent"))?;
        fs::write(&config_path, [0xff, 0xfe])?;
        let ctx = SyncContext::new(Mode::Light, ThemeConfig::default(), &platform)?;

        let err = ensure_k9s_config(&ctx).expect_err("invalid UTF-8 should fail closed");

        assert!(err.to_string().contains("failed to read"));
        assert_eq!(fs::read(config_path)?, [0xff, 0xfe]);
        Ok(())
    }
}
